use card_pack;
db.dropDatabase();

db.dinosaurs.insertMany([
    {
        image: "*.jpg",
        name: "Pachycephalosaurus",
        diet: "Herbivore",
        description: "Pachycephalosaurus is famous for having a large, bony dome atop its skull, up to 25 cm (10 in) thick, which safely cushioned its tiny brain.",
        height: 19.7,
        weight: 6614,
        length: 26.2,
        danger_rating: 2,
        intelligence: 7,
        age: 76,
    },
    {
        image: "*.jpg",
        name: "Tyrannosaurus Rex",
        diet: "Carnivore",
        description: "Tyrannosaurus rex was one of the most ferocious predators to ever walk the Earth. With a massive body, sharp teeth, and jaws so powerful they could crush a car.",
        height: 18.4,
        weight: 13227,
        length: 39.3,
        danger_rating: 9,
        intelligence: 9,
        age: 67,
    },
    {
        image: "*.jpg",
        name: "Barosaurus",
        diet: "Herbivore",
        description: "Barosaurus was a giant, long-tailed, long-necked, plant-eating sauropod dinosaur closely related to the more familiar Diplodocus.",
        height: 85.3,
        weight: 8819,
        length: 85.3,
        danger_rating: 3,
        intelligence: 2,
        age: 156,
    },
    {
        image: "*.jpg",
        name: "Heterodontosaurus",
        diet: "Herbivore",
        description: "Heterodontosaurus is a genus of small omnivorous dinosaur with prominent canine teeth which lived in the early Jurassic of South Africa.",
        height: 1.6,
        weight: 22,
        length: 3.9,
        danger_rating: 1,
        intelligence: 5,
        age: 208,
    },
    {
        image: "*.jpg",
        name: "Suchomimus",
        diet: "Carnivore",
        description: "",
        height: 13.1,
        weight: 11023,
        length: 39.3,
        danger_rating: 8,
        intelligence: 7,
        age: 100,
    },
    {
        image: "*.jpg",
        name: "Pachyrhinosaurus",
        diet: "Herbivore",
        description: "",
        height: 9.8,
        weight: 8000,
        length: 23,
        danger_rating: 2,
        intelligence: 4,
        age: 70,
    },
    {
        image: "*.jpg",
        name: "Compsognathus",
        diet: "Carnivore",
        description: "",
        height: 2.3,
        weight: 6.6,
        length: 4.6,
        danger_rating: 5,
        intelligence: 7,
        age: 145,
    },
    {
        image: "*.jpg",
        name: "Iguanodon",
        diet: "Herbivore",
        description: "",
        height: 16.4,
        weight: 9920,
        length: 32.8,
        danger_rating: 3,
        intelligence: 6,
        age: 135,
    },
    {
        image: "*.jpg",
        name: "Pentaceratops",
        diet: "Herbivore",
        description: "",
        height: 9.8,
        weight: 17636,
        length: 26.2,
        danger_rating: 3,
        intelligence: 5,
        age: 75,
    },
    {
        image: "*.jpg",
        name: "Coelophysis",
        diet: "Carnivore",
        description: "",
        height: 6.6,
        weight: 59.5,
        length: 9.8,
        danger_rating: 4,
        intelligence: 7,
        age: 225,
    },
    {
        image: "*.jpg",
        name: "Velociraptor",
        diet: "Carnivore",
        description: "",
        height: 3.3,
        weight: 33,
        length: 6.6,
        danger_rating: 9,
        intelligence: 10,
        age: 85,
    },
    {
        image: "*.jpg",
        name: "Centrosaurus",
        diet: "Herbivore",
        description: "",
        height: 6.6,
        weight: 2205,
        length: 19.7,
        danger_rating: 2,
        intelligence: 4,
        age: 76,
    },
    {
        image: "*.jpg",
        name: "Megalosaurus",
        diet: "Carnivore",
        description: "",
        height: 9.8,
        weight: 2205,
        length: 29.5,
        danger_rating: 9,
        intelligence: 8,
        age: 175,
    },
    {
        image: "*.jpg",
        name: "Protoceratops",
        diet: "Herbivore",
        description: "",
        height: 4.9,
        weight: 881,
        length: 6.6,
        danger_rating: 2,
        intelligence: 4,
        age: 72,
    },
    {
        image: "*.jpg",
        name: "Giganotosaurus",
        diet: "Carnivore",
        description: "",
        height: 19.7,
        weight: 17636,
        length: 52.5,
        danger_rating: 10,
        intelligence: 7,
        age: 100,
    },
    {
        image: "*.jpg",
        name: "Brachiosaurus",
        diet: "Herbivore",
        description: "",
        height: 52.5,
        weight: 17636,
        length: 85.3,
        danger_rating: 3,
        intelligence: 2,
        age: 156,
    },
    {
        image: "*.jpg",
        name: "Herrerasaurus",
        diet: "Carnivore",
        description: "",
        height: 3.3,
        weight: 772,
        length: 16.4,
        danger_rating: 7,
        intelligence: 6,
        age: 230,
    },
    {
        image: "*.jpg",
        name: "Gallimimus",
        diet: "Omnivore",
        description: "",
        height: 9.8,
        weight: 440.9,
        length: 18.3,
        danger_rating: 5,
        intelligence: 7,
        age: 74,
    },
    {
        image: "*.jpg",
        name: "Triceratops",
        diet: "Herbivore",
        description: "",
        height: 9.8,
        weight: 12125,
        length: 29.5,
        danger_rating: 2,
        intelligence: 4,
        age: 72,
    },
    {
        image: "*.jpg",
        name: "Corythosaurus",
        diet: "Herbivore",
        description: "",
        height: 16.4,
        weight: 11023,
        length: 26.2,
        danger_rating: 2,
        intelligence: 5,
        age: 80,
    },
    {
        image: "*.jpg",
        name: "Maiasaura",
        diet: "Herbivore",
        description: "",
        height: 8.2,
        weight: 6614,
        length: 29.5,
        danger_rating: 2,
        intelligence: 3,
        age: 80,
    },
    {
        image: "*.jpg",
        name: "Dimorphodon",
        diet: "Carnivore",
        description: "",
        height: 0.82,
        weight: 8.8,
        length: 0.82,
        danger_rating: 4,
        intelligence: 4,
        age: 200,
    },
    {
        image: "*.jpg",
        name: "Stegosaurus",
        diet: "Herbivore",
        description: "",
        height: 9.8,
        weight: 6834,
        length: 29.5,
        danger_rating: 2,
        intelligence: 1,
        age: 76,
    },
    {
        image: "*.jpg",
        name: "Stenonychosaurus",
        diet: "Carnivore",
        description: "",
        height: 5.9,
        weight: 132,
        length: 6.6,
        danger_rating: 7,
        intelligence: 10,
        age: 76,
    },
    {
        image: "*.jpg",
        name: "Hypsilophodon",
        diet: "Herbivore",
        description: "",
        height: 2.6,
        weight: 110,
        length: 6.6,
        danger_rating: 1,
        intelligence: 6,
        age: 125,
    },
    {
        image: "*.jpg",
        name: "Camarasaurus",
        diet: "Herbivore",
        description: "",
        height: 29.5,
        weight: 4409,
        length: 59.1,
        danger_rating: 3,
        intelligence: 2,
        age: 150,
    },
    {
        image: "*.jpg",
        name: "Styracosaurus",
        diet: "Herbivore",
        description: "",
        height: 6.6,
        weight: 6614,
        length: 16.4,
        danger_rating: 2,
        intelligence: 3,
        age: 77,
    },
    {
        image: "*.jpg",
        name: "Euoplocephalus",
        diet: "Herbivore",
        description: "",
        height: 5.9,
        weight: 4409,
        length: 19.7,
        danger_rating: 3,
        intelligence: 3,
        age: 76,
    },
    {
        image: "*.jpg",
        name: "Archaeopteryx",
        diet: "Omnivore",
        description: "",
        height: 1,
        weight: 13.2,
        length: 1,
        danger_rating: 6,
        intelligence: 5,
        age: 150,
    },
    {
        image: "*.jpg",
        name: "Oviraptor",
        diet: "Carnivore",
        description: "",
        height: 2.6,
        weight: 44,
        length: 5.9,
        danger_rating: 5,
        intelligence: 8,
        age: 70,
    },
]);	
